[package]
name = "epic_gen_gen"
version = "0.0.1"
edition = "2018"
authors = ["Epic Developers <mimblewimble@lists.launchpad.net>"]
description = "Utility to automate the generation of Epic's genesis block"
license = "Apache-2.0"
repository = "https://github.com/mimblewimble/epic"
keywords = [ "crypto", "epic", "mimblewimble" ]
readme = "README.md"

[[bin]]
name = "gen_gen"
path = "src/bin/gen_gen.rs"

[dependencies]
chrono = "0.4.4"
cuckoo_miner = "1.0.0"
curl = "0.4.19"
epic_core = { path = "../../core" }
epic_chain = { path = "../../chain" }
epic_keychain = { path = "../../keychain" }
epic_miner_plugin = "1.0.0"
epic_store = { path = "../../store" }
epic_util = { path = "../../util" }
epic_wallet = { path = "../../wallet" }
rpassword = "2.0.0"
serde_json = "1"

[patch.crates-io]
epic_api = { path = "../../api" }
epic_core = { path = "../../core" }
epic_chain = { path = "../../chain" }
epic_keychain = { path = "../../keychain" }
epic_util = { path = "../../util" }
epic_wallet = { path = "../../wallet" }
