[package]
name = "epic_api"
version = "3.5.0"
authors = ["Epic Foundation <epiccash@brickabode.com>"]
description = "APIs for epic, a simple, private and scalable cryptocurrency implementation based on the MimbleWimble chain format."
license = "Apache-2.0"
repository = "https://github.com/EpicCash/epic"
keywords = ["crypto", "epic", "mimblewimble"]
workspace = ".."
edition = "2018"

[dependencies]
easy-jsonrpc-mw = "0.5.4"
hyper = { version = "0.14.27", features = ["full"]}
lazy_static = "1"
regex = "1"
ring = "0.16.20"
serde = "1"
serde_derive = "1"
serde_json = "1"
thiserror = "1"
log = "0.4"
tokio = { version = "1.32", features = ["full"] }
tokio-rustls = "0.24.1"

http = "0.2"

futures = "0.3"

url = "2.1"
bigint = "4.4.1"


hyper-rustls = "0.24.1"
hyper-tls = "0.5"
hyper-timeout = "0.4"
rustls-pemfile = "1.0.3"

rustls = "0.21.7"

bytes = "0.5"



epic_core = { path = "../core", version = "3.5.0" }
epic_chain = { path = "../chain", version = "3.5.0" }
epic_p2p = { path = "../p2p", version = "3.5.0" }
epic_pool = { path = "../pool", version = "3.5.0" }
epic_store = { path = "../store", version = "3.5.0" }
epic_util = { path = "../util", version = "3.5.0" }
